# Generated by Django 5.2.8 on 2025-12-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('under_maintenance', 'Under Maintenance'), ('service', 'Validation')], default='operational', max_length=20)),
                ('date_acquired', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.CharField(max_length=100, verbose_name='Performed By (Internal/Vendor)')),
                ('record_type', models.CharField(choices=[('CAL', 'Validation'), ('RPR', 'Repair'), ('SVC', 'Service')], max_length=10)),
                ('instrumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='instruments.instrument')),
            ],
        ),
    ]
