# Generated by Django 5.2.8 on 2025-12-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='instrumen',
            new_name='instrument',
        ),
    ]
